### ISSUE TITLE
Can‘t auto install dependencies when running from other directory than project root

### ISSUE THREAD

**Issue by codenius** [DoctorFuchs/kiosk#20]
```
$ python3 kiosk/run.py 
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
Traceback (most recent call last):
  File "/root/kiosk/run.py", line 57, in <module>
    __import__("flask")
ModuleNotFoundError: No module named 'flask'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/kiosk/run.py", line 59, in <module>
    upgradeDependencies()
  File "/root/kiosk/run.py", line 23, in upgradeDependencies
subprocess.CalledProcessError: Command '['/usr/bin/python3', '-m', 'pip', 'install', '-r', 'requirements.txt', '-t', '/root/kiosk/lib', '--upgrade', '--no-user']' returned non-zero exit status 1.
```

**Comment by codenius** [comment]
Solves with 9567ba6.
