### ISSUE TITLE
App abort‘s after auto installing dependencies (next run is as desired)

### ISSUE THREAD

**Issue by codenius** [DoctorFuchs/kiosk#21]
```
$python3 run.py 
Collecting flask
  Using cached Flask-2.0.2-py3-none-any.whl (95 kB)
Collecting itsdangerous>=2.0
  Using cached itsdangerous-2.0.1-py3-none-any.whl (18 kB)
Collecting click>=7.1.2
  Using cached click-8.0.3-py3-none-any.whl (97 kB)
Collecting Werkzeug>=2.0
  Using cached Werkzeug-2.0.2-py3-none-any.whl (288 kB)
Collecting Jinja2>=3.0
  Using cached Jinja2-3.0.3-py3-none-any.whl (133 kB)
Collecting MarkupSafe>=2.0
  Using cached MarkupSafe-2.0.1.tar.gz (18 kB)
Using legacy 'setup.py install' for MarkupSafe, since package 'wheel' is not installed.
Installing collected packages: MarkupSafe, Werkzeug, Jinja2, itsdangerous, click, flask
    Running setup.py install for MarkupSafe ... done
Successfully installed Jinja2-3.0.3 MarkupSafe-2.0.1 Werkzeug-2.0.2 click-8.0.3 flask-2.0.2 itsdangerous-2.0.1
Traceback (most recent call last):
  File "/root/kiosk/run.py", line 57, in <module>
    __import__("flask")
ModuleNotFoundError: No module named 'flask'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/kiosk/run.py", line 60, in <module>
    __import__("flask")
ModuleNotFoundError: No module named 'flask'
$python3 run.py 
 * Running on http://localhost:1024/ (Press CTRL+C to quit)

```

**Comment by codenius** [comment]
Fixed by cfaecfb

**Comment by codenius** [comment]
Problem probably still exists. More tests are needed.
