### ISSUE TITLE
Double run aborts

### ISSUE THREAD

**Issue by codenius** [DoctorFuchs/kiosk#22]
```
$ python3 run.py 
Traceback (most recent call last):
  File "run.py", line 64, in <module>
    server.main(args)
  File "backend/server.py", line 70, in main
    run_simple('localhost', 1024, application, use_reloader=False, use_debugger=False, use_evalex=True)
  File "/home/benutzer/.local/lib/python3.6/site-packages/werkzeug/serving.py", line 1010, in run_simple
    inner()
  File "/home/benutzer/.local/lib/python3.6/site-packages/werkzeug/serving.py", line 959, in inner
    fd=fd,
  File "/home/benutzer/.local/lib/python3.6/site-packages/werkzeug/serving.py", line 798, in make_server
    host, port, app, request_handler, passthrough_errors, ssl_context, fd=fd
  File "/home/benutzer/.local/lib/python3.6/site-packages/werkzeug/serving.py", line 688, in __init__
    super().__init__(server_address, handler)  # type: ignore
  File "/usr/lib/python3.6/socketserver.py", line 456, in __init__
    self.server_bind()
  File "/usr/lib/python3.6/http/server.py", line 136, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/lib/python3.6/socketserver.py", line 470, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
```

**Comment by codenius** [comment]
At least a friendly error message should be displayed and the program should also continue the run to make sure that the browser window starts, for example.
