### ISSUE TITLE
Error after auto dependencies installation at first run (beta)

### ISSUE THREAD

**Issue by codenius** [DoctorFuchs/kiosk#32]
```
Traceback (most recent call last):
  File "/root/kiosk/run.py", line 74, in <module>
    import server
  File "/root/kiosk/backend/server.py", line 5, in <module>
    from api import api
  File "/root/kiosk/backend/api.py", line 12, in <module>
    if not os.path.isdir(storageDir): os.mkdir(__file__.replace(f"backend{os.sep}shop.py", "storages"))
FileExistsError: [Errno 17] File exists: '/root/kiosk/backend/api.py'
```

**Comment by codenius** [comment]
**Error at first rum after auto dependencies installation**
```
Traceback (most recent call last):
  File "/root/kiosk/run.py", line 74, in <module>
    import server
  File "/root/kiosk/backend/server.py", line 5, in <module>
    from api import api
  File "/root/kiosk/backend/api.py", line 12, in <module>
```

**Comment by codenius** [comment]
Both are related to storages folder because they don't occur when creating it manually.

**Comment by codenius** [comment]
Please consider the 5th line in run.py while fixing. The working directory is set to projects root directory.
