### ISSUE TITLE
Cant run beta_2 at 12b1f64

### ISSUE THREAD

**Issue by codenius** [DoctorFuchs/kiosk#41]
`python3 -m server` gives
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/user/directory/kiosk/server/__main__.py", line 3, in <module>
    from server.utils.config_reader import config
  File "/home/user/directory/kiosk/server/utils/config_reader.py", line 3, in <module>
    from server.__main__ import ABS_MODULE_PATH
  File "/home/user/directory/kiosk/server/__main__.py", line 3, in <module>
    from server.utils.config_reader import config
ImportError: cannot import name 'config' from partially initialized module 'server.utils.config_reader' (most likely due to a circular import) (/home/user/directory/kiosk/server/utils/config_reader.py)
```

**Comment by DoctorFuchs** [comment]
I will fix it today
